# Generated by Django 5.2.5 on 2025-08-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ngo',
            name='area_manager',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ngo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='ngo',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ngo',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='ngo_profiles/'),
        ),
        migrations.AddField(
            model_name='ngo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ngo',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
