# Generated by Django 5.2.5 on 2025-08-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_worker_permit_updated_at_permit_workers'),
    ]

    operations = [
        migrations.AddField(
            model_name='permit',
            name='permit_type',
            field=models.CharField(choices=[('NGO', 'NGO Permit'), ('FOREIGN_WORKER', 'Foreign Worker Permit')], default='NGO', max_length=20),
        ),
    ]
